# Generated by Django 5.2.5 on 2025-08-29 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_rename_name_order_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость продукта'),
        ),
    ]
