# Generated by Django 5.2.5 on 2025-08-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20250829_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting_for_acceptation', 'Ожидает подтверждения'), ('sent_to_restaurant', 'Передан в ресторан'), ('given_to_courier', 'Передан курьеру'), ('completed', 'завершен')], default='waiting_for_acceptation', max_length=30, verbose_name='статус заказа'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='foodcartapp_status_99d57e_idx'),
        ),
    ]
