# Generated by Django 5.2.5 on 2025-08-31 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_comment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_status_99d57e_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата и время звонка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата и время доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='registrated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время заказа'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'registrated_at', 'called_at', 'delivered_at'], name='foodcartapp_status_ac0634_idx'),
        ),
    ]
