# Generated by Django 5.2.5 on 2025-08-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_alter_order_called_at_alter_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('electronic', 'Электронно')], default='cash', max_length=30, verbose_name='способ оплаты'),
        ),
    ]
