# Generated by Django 5.2.5 on 2025-08-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('electronic', 'Электронно'), ('unknown', 'Не указан')], default='unknown', max_length=30, verbose_name='способ оплаты'),
        ),
    ]
