# Generated by Django 5.2.5 on 2025-08-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_status_ac0634_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'registrated_at', 'called_at', 'delivered_at', 'payment_method'], name='foodcartapp_status_129823_idx'),
        ),
    ]
