# Generated by Django 5.2.5 on 2025-08-31 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_remove_order_foodcartapp_status_ac0634_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cooking_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcartapp.restaurant', verbose_name='Ресторан, готовящий заказ'),
        ),
    ]
