# Generated by Django 5.2.5 on 2025-09-01 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_cooking_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'локация',
                'verbose_name_plural': 'локации',
            },
        ),
        migrations.CreateModel(
            name='OrderLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='foodcartapp.order', verbose_name='заказ')),
                ('point_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_origin', to='foodcartapp.location', verbose_name='точка А (ресторан)')),
                ('point_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_destination', to='foodcartapp.location', verbose_name='точка B (клиент)')),
            ],
            options={
                'verbose_name': 'локация заказа',
                'verbose_name_plural': 'локации заказов',
            },
        ),
    ]
