# Generated by Django 5.2.5 on 2025-09-01 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_alter_orderlocation_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость продукта'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['lat', 'lng'], name='foodcartapp_lat_cc2ff7_idx'),
        ),
    ]
