# Generated by Django 5.2.5 on 2025-09-03 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_alter_orderproduct_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость продукта'),
        ),
    ]
