# Generated by Django 5.2.5 on 2025-09-03 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_alter_orderproduct_final_price'),
        ('geolocations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlocation',
            name='point_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_destination', to='geolocations.location', verbose_name='точка B (клиент)'),
        ),
        migrations.AlterField(
            model_name='orderlocation',
            name='point_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_origin', to='geolocations.location', verbose_name='точка А (ресторан)'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
