# Generated by Django 5.2.5 on 2025-09-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_orderlocation_point_b_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderLocation',
        ),
    ]
