# Generated by Django 5.2.5 on 2025-09-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'локация',
                'verbose_name_plural': 'локации',
                'indexes': [models.Index(fields=['lat', 'lng'], name='geolocation_lat_3a964c_idx')],
            },
        ),
    ]
