# Generated by Django 5.2.5 on 2025-09-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='location',
            new_name='foodcartapp_lat_cc2ff7_idx',
            old_name='geolocation_lat_3a964c_idx',
        ),
        migrations.AlterModelTable(
            name='location',
            table='foodcartapp_location',
        ),
    ]
