# Generated by Django 5.2.5 on 2025-09-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0002_rename_geolocation_lat_3a964c_idx_foodcartapp_lat_cc2ff7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='location',
            name='foodcartapp_lat_cc2ff7_idx',
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Адрес'),
        ),
        migrations.AlterModelTable(
            name='location',
            table=None,
        ),
    ]
